### PR TITLE
chore: replace custom utils functions with k8s.io/kubernetes library

### PR DESCRIPTION
**Pull request by fmuyassarov**
Fixes https://github.com/kubernetes-sigs/karpenter/issues/1275

**Description**
Replace custom utils function `IsTerminal()` with k8s.io/kubernetes library function `IsPodTerminal()`.

**How was this change tested?**
```
make install-kwok
make apply
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@jonathan-innis @njtran I noticed that there is a common issue with the govulncheck failing due to some vulnerabilities found in the netip and I fixed it [here](https://github.com/kubernetes-sigs/karpenter/pull/1298/commits/2e8d3a0ee4088e657b97dfa9989ba623e3fc31d0) so that the patch doesn't fail required checks.

**Comment by njtran** [comment]
@fmuyassarov go vuln should be fixed now

**Review by njtran — COMMENTED** [review]
/lgtm
/approve

**Comment by njtran** [comment]
Thanks for the commit!

**Comment by jonathan-innis** [comment]
@fmuyassarov I think this change may have broken dependency resolution when trying to build with this latest version now. We can't directly use the upstream `kubernetes/kubernetes` go module because it references a bunch of local modules with pseudo-versions (v0.0.0) and then does a bunch of [replace statements at the bottom](https://github.com/kubernetes/kubernetes/blob/9e2075b3c87061d25759b0ad112266f03601afd8/go.mod#L227). Any downstream packages that consume this directly would also have to do replace statements, which is the reason why k8s went out and created a bunch of distinct packages that they publish separately (conroller-runtime, apimachinery, etc)

I did a bit of searching around but I'm not sure there's a utils package that exists in upstream right now that contains this function. Maybe @dims or @sftim has more insight if there's some work that we could do here to move these kinds of utils functions into a distinct package.

**Comment by fmuyassarov** [comment]
Sorry that I didn't notice the possible issue with the dependency resolution. Probably because I'm using vscode.
If we need this to be fixed asap for developers, I'm fine to revert that commit for the time being.

**Comment by dims** [comment]
+1 to revert! please avoid depending on `k8s.io/kubernetes` ( documented here - https://github.com/kubernetes/kubernetes?tab=readme-ov-file#to-start-using-k8s )

If you do need some things from there, please open an issue and propose a good landing spot in one of the staging repositories:
https://github.com/kubernetes/kubernetes/tree/master/staging#external-repository-staging-area

**Comment by fmuyassarov** [comment]
> +1 to revert! please avoid depending on `k8s.io/kubernetes` ( documented here - https://github.com/kubernetes/kubernetes?tab=readme-ov-file#to-start-using-k8s )
> 
@jonathan-innis I have filed a revert patch in https://github.com/kubernetes-sigs/karpenter/pull/1302. PTAL

**Pull request merged**
