### PR TITLE
chore: Display CPU and Memory on nodepools, with -o wide you also get limits!

### LINKED ISSUE #1054: Add CPU/Memory visibility on nodepools CRD for kubectl get (through additionalPrinterColumns)
### Description

**What problem are you trying to solve?** I found myself using describe on nodepools to get access to CPU/Memory information and realized it could be displayed in the get for a faster approach

**How important is this feature to you?** It's a life-improvement feature, and it's not perfect as we are limited in what can be done in additionalPrinterColumns for kubectl

See PR #1055 for what this looks like.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by ROunofF**
Fixes #1054  

**Description**: Added information already available so it's visible in the kubectl get

Output : 
```
[karpenter]$ k get nodepools.karpenter.sh
NAME            NODECLASS       CPU   MEMORY
default         default         10    19846992Ki
karpenter-pub   karpenter-pub
karpenter-wl1   karpenter-wl1

[karpenter]$ k get nodepools.karpenter.sh -o wide
NAME            NODECLASS       CPU   CPU_LIMIT   MEMORY       MEM_LIMIT   WEIGHT
default         default         10    500         19846992Ki   20Ti
karpenter-pub   karpenter-pub         1k
karpenter-wl1   karpenter-wl1         400
```

**How was this change tested?**: make build && make test && kubectl apply -f karpenter.sh_nodepools.yaml

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jonathan-innis** [comment]
This is a cool idea and something that we are actively thinking about for v1 as we are going through our API design! What's the reason that you think that this would be generally useful to all users? I'm curious how you are using this.

Realistically, if you want an easy out to get this printed on your side right now, you can try using [`kubectl` custom columns](https://kubernetes.io/docs/reference/kubectl/#:~:text=Description-,%2Do%20custom%2Dcolumns,-%3D%3Cspec%3E).

**Comment by jonathan-innis** [comment]
@ROunofF If you're interested in proposing this as another change that we should do at v1, we'd definitely welcome you proposing it in https://github.com/kubernetes-sigs/karpenter/issues/758 and describing your use-case for adding it alongside why you think this could be really useful for all users.

**Comment by ROunofF** [comment]
> This is a cool idea and something that we are actively thinking about for v1 as we are going through our API design! What's the reason that you think that this would be generally useful to all users? I'm curious how you are using this. I saw that you mentioned in #1054 that you felt limited by the additionalPrinterColumns, so I'm curious in your ideal world what you would like the printer columns to look like for `kubectl get nodeclaims`, `kubectl get nodepools` and `kubectl get <insert-cloudproivder-type>nodeclasses`
> 
> Realistically, if you want an easy out to get this printed on your side right now, you can try using [`kubectl` custom columns](https://kubernetes.io/docs/reference/kubectl/#:~:text=Description-,%2Do%20custom%2Dcolumns,-%3D%3Cspec%3E).

**Nodeclaims**: I'm happy with the current output didn't need anything that isn't included yet.

**Nodepools**: As the PR did, it's interesting to see the current provisioned "total" of CPU and Memory as well as weight so that I view the cluster activity vs the nodepools I have configured. I'm using an on-demand and bursting into a spot pool. For the limit, I was more interested in the % usage however the additionalPrinterColumns doesn't allow calculation, and the other improvement I would have made was to output using a unit so that number wouldn't be longer than 3(or 4?) digits 5.xy - 500 + units ( 19846992Ki would be printed as 18.9Gi)

My initial Sketch was something like this :
```
[karpenter]$ k get nodepools.karpenter.sh -o wide
NAME            NODECLASS       CPU / LIMIT %CPU  MEM / LIMIT %MEM  WEIGHT
default          default                     10 / 500     2%      18.9Gi / 20Ti   0.1%.      10
karpenter-pub   karpenter-pub       - / 1k      0%           -                    0%       10
karpenter-wl1   karpenter-wl1         - / 400.   0%          -                    0%       20
```

**awsnodetemplates**: This one is pretty static for me, so I rarely look at it. Looking at the possibilities here, the list of resolved security groups, subnets and AMI-ids could be of interest but the full details will be hard to represent.

**Comment by nerzhul** [comment]
> > This is a cool idea and something that we are actively thinking about for v1 as we are going through our API design! What's the reason that you think that this would be generally useful to all users? I'm curious how you are using this. I saw that you mentioned in #1054 that you felt limited by the additionalPrinterColumns, so I'm curious in your ideal world what you would like the printer columns to look like for `kubectl get nodeclaims`, `kubectl get nodepools` and `kubectl get <insert-cloudproivder-type>nodeclasses`
> > Realistically, if you want an easy out to get this printed on your side right now, you can try using [`kubectl` custom columns](https://kubernetes.io/docs/reference/kubectl/#:~:text=Description-,%2Do%20custom%2Dcolumns,-%3D%3Cspec%3E).
> 
> **Nodeclaims**: I'm happy with the current output didn't need anything that isn't included yet.
> 
> **Nodepools**: As the PR did, it's interesting to see the current provisioned "total" of CPU and Memory as well as weight so that I view the cluster current provisioned state vs the nodepools I have configured. I'm using an on-demand pool and bursting into a spot pool as well as specific pool for some applications (think gpu/custom resources). For the limit, I was more interested in the % usage however the additionalPrinterColumns doesn't allow calculation, and the other improvement I would have made was to output using a unit so that number wouldn't be longer than 3(or 4?) digits 5.xy - 500 + units ( 19846992Ki would be printed as 18.9Gi)
> 
> My initial Sketch was something like this :
> 
> ```
> [karpenter]$ k get nodepools.karpenter.sh -o wide
> NAME            NODECLASS       CPU / LIMIT %CPU  MEM / LIMIT  %MEM  WEIGHT
> default         default          10 / 500     2%  18.9Gi/20Ti   0.1%      10
> karpenter-pub   karpenter-pub     - / 1k      0%          -     0%       10
> karpenter-wl1   karpenter-wl1     - / 400     0%          -     0%       20
> ```
> 
> **awsnodetemplates**: This one is pretty static for me, so I rarely look at it. Looking at the possibilities here, the list of resolved security groups, subnets and AMI-ids could be of interest but the full details will be hard to represent.

Clearly a very nice output. We have a custom node controller at work and we are moving bricks to karpenter and evaluating, people like very much the % use output in kubectl, if we can have the same on nodepool it would be great

**Comment by jonathan-innis** [comment]
> people like very much the % use output in kubectl, if we can have the same on nodepool it would be great

This is super interesting. If we didn't have the percentage output, would that be enough? I'm trying to avoid adding a status field _only_ for the purpose of having that value output in printer columns. The other thing: Do we need the same thing for ephemeral storage or do we think that everyone largely just cares about CPU and memory? What if we printed the number of nodes that were tied to the NodePool? Would you want that printed as part of the printer columns? What if we had details on the number of disruptions that are currently allowed for the NodePool through the budgets? Would you want this printed in the printer columns? What about the current number of disrupted nodes? 

There's going to be a lot of discussion on this once the v1 API RFC comes out, but I'm glad that we're starting the discussion on this now.

**Comment by ROunofF** [comment]
> > people like very much the % use output in kubectl, if we can have the same on nodepool it would be great
> 
> This is super interesting. If we didn't have the percentage output, would that be enough? 

Yes, the percentage was just my initial idea, and it's easier to use in some kind of monitoring tool. But as humain, we can still figure out head-room with the real count...

**Comment by igor-nikiforov** [comment]
> If we didn't have the percentage output, would that be enough?

I personally think that both values and percentage is important, when it combined it immediately helps to get overall picture. Like when you use `kubectl get node`.

> What if we printed the number of nodes that were tied to the NodePool?

This is definitely what is missing here (especially when combined with https://github.com/kubernetes-sigs/karpenter/pull/1160) 

> What if we had details on the number of disruptions that are currently allowed for the NodePool through the budgets? Would you want this printed in the printer columns? What about the current number of disrupted nodes?

This could part of `-owide` but most time users care only about used and available resources.

The ideal sketch from me is something like this:
```
NAME              NODECLASS         CPU                MEMORY                     NODES      WEIGHT
default           default            - / 46  (0 %)     16 Gi / 128 Gi (12.5%)     - / 10     10
karpenter-pub     karpenter-pub     10 / 500 (2 %)         - / 72 Gi  (0 %)       2 / 10     10
```

**Pull request closed without merging**
