### PR TITLE
chore: Adding cherry picked commits to `release-v0.32.x`

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #N/A 

**Description**
- Adding in cherry picked commits to the v0.32.x release branch

**How was this change tested?**
- N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — APPROVED** [review]
/lgtm
/approve

**Review by jonathan-innis — APPROVED** [review]
/lgtm
/approve

**Review by njtran — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
