### PR TITLE
chore: add script for install kube-prometheus.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
/kind cleanup
Fixes #N/A 

**Description**

use script to install kube-promethues, to make it easier for people to get started locally karpenter.

**How was this change tested?**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
cc @njtran

**Comment by liangyuanpeng** [comment]
not releated
```shell
[AfterSuite] PASSED [0.000 seconds]
------------------------------

Summarizing 1 Failure:
  [FAIL] Performance Provisioning [It] should do complex provisioning
  /home/runner/work/karpenter/karpenter/test/suites/perf/scheduling_test.go:112

Ran 4 of 4 Specs in 886.065 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestPerf (886.07s)
FAIL
FAIL	sigs.k8s.io/karpenter/test/suites/perf	886.097s
FAIL
```

**Comment by liangyuanpeng** [comment]
rebased

**Review by jonathan-innis — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
